# Generated by Django 4.2.4 on 2023-08-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_departments_dep_decription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='dep_decription',
            field=models.TextField(max_length=800),
        ),
    ]
